# DMZ ağındaki VPN gateway ve NAS cihazları buradan RADIUS isteği gönderebilir.
client localhost {
    ipaddr          = 127.0.0.1
    secret          = testing123
    require_message_authenticator = no
}

client dmz_network {
    ipaddr          = 192.168.100.0/24
    proto           = *
    secret          = changeme_shared_secret   # .env / secrets'a taşınacak
    require_message_authenticator = yes
    nas_type        = other
}

client internal_network {
    ipaddr          = 192.168.101.0/24
    proto           = *
    secret          = changeme_shared_secret
    require_message_authenticator = yes
    nas_type        = other
}
