eap {
    default_eap_type = tls

    timer_expire     = 60
    ignore_unknown_eap_types = no
    cisco_accounting_username_bug = no
    max_sessions = 4096

    tls-config tls-common {
        private_key_password = whatever
        private_key_file = /etc/freeradius/3.0/certs/server.pem
        certificate_file  = /etc/freeradius/3.0/certs/server.pem
        ca_file           = /etc/freeradius/3.0/certs/ca.pem

        # Sunucu ve istemci sertifikaları burada doğrulanır.
        # Sertifika CN/alan bilgisi Policy Engine (FastAPI) tarafında
        # admin/employee/guest profiline eşlenecek.
        fragment_size = 1024
        include_length = yes
        check_crl = no
        cipher_list = "DEFAULT"
    }

    tls {
        tls = tls-common
    }
}
